### ISSUE TITLE
gulp报错

### ISSUE THREAD

**Issue by mynameisa** [fabric-lab/fabric-manager#1]
我的环境是docker的golang镜像的容器，在构建前端代码的时候报错如下图：  
![image](https://user-images.githubusercontent.com/15168088/46900785-75d6bd80-ceda-11e8-8b17-b83765560b0f.png)  
启动后台程序以后：  
![image](https://user-images.githubusercontent.com/15168088/46900795-b7ffff00-ceda-11e8-8b76-b4de0ab4146b.png)  
请问是哪里出了问题呢

**Comment by fabric-lab** [comment]
应该是执行bower命令失败，没有下载到相关依赖文件，你手动执行一下 
bower install --allow-root
