### ISSUE TITLE
界面无法访问

### ISSUE THREAD

**Issue by hadoop835** [fabric-lab/fabric-manager#2]
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/entity/:entity       --> github.com/fabric-lab/fabric-manager/server/pkg.GetEntitys (4 handlers)
[GIN-debug] GET    /api/entity/:entity/:id   --> github.com/fabric-lab/fabric-manager/server/pkg.GetEntity (4 handlers)
[GIN-debug] GET    /api/entity/:entity/:id/state --> github.com/fabric-lab/fabric-manager/server/pkg.GetNodeState (4 handlers)
[GIN-debug] POST   /api/entity/:entity/:id   --> github.com/fabric-lab/fabric-manager/server/pkg.CreateEntity (4 handlers)
[GIN-debug] PUT    /api/entity/:entity/:id/cmd --> github.com/fabric-lab/fabric-manager/server/pkg.ExecCMD (4 handlers)
[GIN-debug] DELETE /api/entity/:entity/:id   --> github.com/fabric-lab/fabric-manager/server/pkg.DelEntity (4 handlers)
[GIN-debug] GET    /api/organizations/:id/:ca --> github.com/fabric-lab/fabric-manager/server/pkg.GetCert (4 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2018/10/16 - 14:57:20 | 404 |           1ms |             ::1 | GET      /
[GIN] 2018/10/16 - 14:57:21 | 404 |            0s |             ::1 | GET      /
[GIN] 2018/10/16 - 14:57:22 | 404 |            0s |             ::1 | GET      /
[GIN] 2018/10/16 - 14:57:22 | 404 |           1ms |             ::1 | GET      /
[GIN] 2018/10/16 - 14:57:23 | 404 |            0s |             ::1 | GET      /

**Comment by fabric-lab** [comment]
你是下载的release版本，还是自己搭建的开发环境，如果是自己搭建的开发环境，请确保前端正常启动
cd fabric-manager/app && npm install && gulp
